### ISSUE TITLE
ETA on shinysee (webcam)?

### ISSUE THREAD

**Issue by daattali** [nstrayer/shinysense#21]
I see the package hasn't been touched in 6 months and the README says shinysee is "coming soon". Is that still in the works or has this project been neglected?

**Comment by nstrayer** [comment]
Project _has_ been neglected but is not off. This may provide the push I need to start working on this one again. It would be valuable I think especially with all the cool Magick stuff going on. 

Not sure I can fully commit to an ETA but as soon as I get some free time I will make this my first open-source priority. Thanks for letting me know there's interest!

**Comment by daattali** [comment]
No worries, I definitely understand it can be hard to implement additional features to an already working package when it's all open source and you have to use your free time for it. I remember seeing some questions about how to do this on some forum recently and today someone else asked me about how to use webcam in shiny, I started working on a javascript solution and then remembered to look here :)

**Comment by nstrayer** [comment]
So I got this working in a rather sparse but functional way. As of commit fe41ad9315da83289745bde25060dcea64238e10, it's working on the branch `viewR`. 

Right now it lets you take a single photo based on a supplied resolution at a time due to shiny's restriction about message passing being strings making video infeasible atm. Check out the demo app at `demos/shinyviewr_demo.R` for it in action. 

I'll write up a much more thorough intro to it shortly but figured I'd ping you to let you know something is in and working!

**Comment by daattali** [comment]
Sounds good, thanks! I'm not sure how to deal with videos but it's a good
start. Maybe it can create a video file locally and let hte user download
it? I'm not sure, I have no idea how this stuff works anyway :)

---
Dean Attali
President & CEO
AttaliTech Ltd
http://AttaliTech.com <http://attalitech.com>

**Comment by nstrayer** [comment]
`shinyviewr` is now in and (sparsely) documented as of https://github.com/nstrayer/shinysense/pull/22. 

[This blog post](http://livefreeordichotomize.com/2018/07/22/shinyviewr-camera-input-for-shiny/) has a bit more detail on usage. 

Thanks for the impetus!
