### ISSUE TITLE
looks like no device motion is supported on this device :(

### ISSUE THREAD

**Issue by angelobj** [nstrayer/shinysense#26]
Hi Nick:
I was using the movr module without problems, but now it gives me an error message: 'looks like no device motion is supported on this device :('.
If I go to your shinyapps.io Demo, there are no problem, I also uploaded to my account and works great (https://angelobj.shinyapps.io/movr/). But the same code does not work in my computer or my own server (http://206.81.11.114.xip.io:3838/sample-apps/movr/). Any idea of where the problem could be?

**Comment by angelobj** [comment]
I was looking around and it might because Apple blocked the use of motion sensors by default in ios 12 version. My site is not secure (I don't have a SSL certificate) and that might be the problem. I will see if the problem persists on android devices...

**Comment by nstrayer** [comment]
This is almost assuredly because you will need a https site to access any of the device sensors. This is a good idea for privacy but unfortunately makes these things difficult with regards to shinysense. I'm still trying to figure out an idea workflow for these things. 

The only solution would be to use something like a port forwarding app (I've used Termius before) to forward your app from a server to a localhost port which then does away with the need for ssl. That's obviously not ideal, though!

**Comment by nstrayer** [comment]
Android may work because they have tended to be more lax with these privacy issues but I would imagine if they don't already block it they will soon.

**Comment by angelobj** [comment]
I was able to use it in Android, but I need it for ios also, so I went for a certificate installation on my server... It works flawlesly now.

**Comment by nstrayer** [comment]
So this is caused by apple locking down the motion detection for iOS devices due to potential motion fingerprinting. You can enable it again by either using the chrome browser on iOS or going to the main settings menu and then safari > allow motion. I added a more meaningful error message about this to the function in https://github.com/nstrayer/shinysense/pull/34.
